In [13]:
import numpy as np

In [14]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [15]:
random_array = np.random.randint(0,10, size = (3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]], dtype=int32)

In [16]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 ]])

# Dot Product Example (nut butter sales)

In [17]:
np.random.seed(0)
# number of jars sold
sales_amounts = np.random.randint(20, size = (5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [18]:
#Create a weekly sales DF
import pandas as pd 
weekly_sales = pd.DataFrame(sales_amounts,
                            index = ["mon", "tue","wed", "thurs", "fri"],
                            columns = ['almond', 'peanut', 'cashew'])
weekly_sales

almond  peanut  cashew
mon        12      15       0
tue         3       3       7
wed         9      19      18
thurs       4       6      12
fri         1       6       7

In [19]:
prices = np.array([10,8,12])


In [20]:
# create butter_prices df
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["price"], columns=['almond', 'peanut', 'cashew'])
butter_prices

almond  peanut  cashew
price      10       8      12

In [24]:
prices.shape

(3,)

In [26]:
sales_amounts.shape

(5, 3)

In [28]:
#shapes are not aligned - transpose
total_sales = np.dot(prices, sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [29]:
# create daily sales 
butter_prices

almond  peanut  cashew
price      10       8      12

In [30]:
weekly_sales

almond  peanut  cashew
mon        12      15       0
tue         3       3       7
wed         9      19      18
thurs       4       6      12
fri         1       6       7

In [31]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [32]:
daily_sales = np.dot(butter_prices, weekly_sales.T)
daily_sales

array([[240, 138, 458, 232, 142]])

In [33]:
weekly_sales

almond  peanut  cashew
mon        12      15       0
tue         3       3       7
wed         9      19      18
thurs       4       6      12
fri         1       6       7

In [36]:
weekly_sales['total'] = daily_sales.T

In [38]:
weekly_sales

almond  peanut  cashew  total
mon        12      15       0    240
tue         3       3       7    138
wed         9      19      18    458
thurs       4       6      12    232
fri         1       6       7    142

In [43]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3.3],
               [4,5,6.5]])

In [44]:
a1

array([1, 2, 3])

In [45]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [46]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [48]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]], dtype=int32)

In [50]:
np.sort(random_array)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]], dtype=int32)

In [51]:
np.argsort(random_array)

array([[1, 2, 3, 4, 0],
       [1, 2, 0, 3, 4],
       [0, 4, 3, 1, 2]])